language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - chmod a+x ~/.local/bin/stack

install:
  - stack setup --no-terminal
  - stack test --no-terminal  --only-snapshot

script:
  - stack test --no-terminal